[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/go-linkedin"
  to     = "https://www.linkedin.com/in/pranav-reveendran/"
  status = 301

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
